### ISSUE TITLE
[FEATURE] Force Queue

### ISSUE THREAD

**Issue by RemainingToast** [AlexProgrammerDE/PistonQueue#10]
Basically when the main server goes down, currently in my setup (other people probably have similar). But when my main server goes down the rest of the network stays up only the main goes down.

So an option to force players into the queue to wait until the main server is back would be optimal.

**Comment by AlexProgrammerDE** [comment]
Being worked on! Will be part of the next release.

**Comment by RemainingToast** [comment]
Added
