### ISSUE TITLE
permission can't login 

### ISSUE THREAD

**Issue by VozDeOuro** [AlexProgrammerDE/PistonQueue#13]
i have a full permission on the server and when i join i got stuck on the queue server 
and other players without those permission can join perfectly.

as you see i dind't get redirected to main server
 
![image](https://user-images.githubusercontent.com/36045463/115953191-5c0d8c80-a4c0-11eb-9dd8-bce69591070d.png)

**Comment by AlexProgrammerDE** [comment]
I think it is because queue.bypass permission doesn't work. I will send a build later that should resolve this issue.

**Comment by VozDeOuro** [comment]
you will send a build this month ?

**Comment by AlexProgrammerDE** [comment]
@VozDeOuro https://github.com/AlexProgrammerDE/PistonQueue/suites/2513198534/artifacts/54375834

**Comment by VozDeOuro** [comment]
> 
> 
> @VozDeOuro https://github.com/AlexProgrammerDE/PistonQueue/suites/2513198534/artifacts/54375834

same problem with the PistonQueue-2.1.0.jar
din't test the original one :)

**Comment by AlexProgrammerDE** [comment]
@VozDeOuro hm can you show me your permissions inside luckperms? (On bungeecord)

**Comment by VozDeOuro** [comment]
those are the perms 
![image](https://user-images.githubusercontent.com/36045463/115954680-9d099f00-a4c8-11eb-9773-7da8adaf6b1b.png)

**Comment by AlexProgrammerDE** [comment]
@VozDeOuro try this: https://github.com/AlexProgrammerDE/PistonQueue/suites/2573069915/artifacts/56093210

**Comment by VozDeOuro** [comment]
this one works :)

> 
> 
> @VozDeOuro try this: https://github.com/AlexProgrammerDE/PistonQueue/suites/2573069915/artifacts/56093210

realy thx for the fast fix

**Comment by AlexProgrammerDE** [comment]
@VozDeOuro oh, sorry. I think this one should fix that error: https://github.com/AlexProgrammerDE/PistonQueue/suites/2574187573/artifacts/56119211

**Comment by VozDeOuro** [comment]
this release fix the permission problem but now i'm getting flood on chat 
![image](https://user-images.githubusercontent.com/36045463/115982908-a81a0900-a574-11eb-8cb5-1abecda4faee.png)
![image](https://user-images.githubusercontent.com/36045463/115982926-bb2cd900-a574-11eb-9581-b36fcc62234e.png)

seams to be reconecting me multiples time 
![image](https://user-images.githubusercontent.com/36045463/115982937-cd0e7c00-a574-11eb-8f95-129122a01f54.png)

**Comment by AlexProgrammerDE** [comment]
I will be looking into it. Sorry for the inconvenience.

**Comment by VozDeOuro** [comment]
do you want my pistonqueue config ?

**Comment by AlexProgrammerDE** [comment]
Nah i don’t Need it. I will do my own testing later.

Von: Voz De Ouro
Gesendet: Sonntag, 25. April 2021 08:41
An: AlexProgrammerDE/PistonQueue
Cc: Alex; Comment
Betreff: Re: [AlexProgrammerDE/PistonQueue] permission can't login (#13)

do you want my pistonqueue config ?

**Comment by AlexProgrammerDE** [comment]
Looking into this again atm. Will let you know when I know more.

**Comment by AlexProgrammerDE** [comment]
This should have been fixed in the latest release. Let me know if it still occurs or not!
