### ISSUE TITLE
Chunks do not load on the queue server

### ISSUE THREAD

**Issue by TheAwesome98-Real** [AlexProgrammerDE/PistonQueue#19]
I want to make a parkour in the end (yes I know that's a bad idea but i get next to no players so i think it's okay), but the game report's I'm outside of the world, but if i run commands relating to blocks (like setblock) they work. is this a bug, or is my game configured wrong?

**Comment by mcsim415** [comment]
Delete protocolib plugin.
Maybe It will work.
But I don't recommend this.

As you can see at https://github.com/AlexProgrammerDE/PistonQueue/wiki/Setting-up-the-Queue-server#playable-queue-server.
> A playable queue is not recommended as this causes issues and may make your server lag or have high CPU usage and possibly make the queue crash.

**Comment by TheAwesome98-Real** [comment]
ah okay thanks!

I know that's a bad idea, but if you read it it says:
> yes I know that's a bad idea but i get next to no players so i think it's okay
